//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentDetail
    {
        public int AdjustmentDetailId { get; set; }
        public Nullable<int> AdjustmentId { get; set; }
        public string ItemNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Reason { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
