//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int EmployeeId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Intent { get; set; }
        public string PageHeader { get; set; }
        public string PageId { get; set; }
        public string ExtraDetail { get; set; }
    }
}
